name: Publish release artifacts

on:
  release:
    types: 
      - created

env:
  REGISTRY: ghcr.io
  GO_VERSION: "1.21.5"

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v') == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: Generate operator hub bundle
        run: make bundle
      - name: Generate release artifacts
        run: make artifacts
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/alexandrevilain/temporal-operator
          tags: |
            type=ref,event=tag
      - name: Build and push operator docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Docker meta bundle
        id: metabundle
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/alexandrevilain/temporal-operator-bundle
          tags: |
            type=ref,event=tag
      - name: Build and push bundle docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: bundle.Dockerfile
          push: true
          tags: ${{ steps.metabundle.outputs.tags }}
          labels: ${{ steps.metabundle.outputs.labels }}
      - name: Docker meta example worker-process
        id: workerprocess
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/alexandrevilain/example-worker-process
          tags: |
            type=ref,event=tag
      - name: Build and push worker-process docker image
        uses: docker/build-push-action@v5
        with:
          context: ./examples/worker-process/helloworld
          push: true
          tags: ${{ steps.workerprocess.outputs.tags }}
          labels: ${{ steps.workerprocess.outputs.labels }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/release/artifacts/*.yaml
          